version: '3.5'

services:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - loki
    volumes:
      - grafana:/var/lib/grafana
      # TODO put the config file somewhere else than /var which doesn't seem like the best place for a config file
      - ${SHARED_DIRECTORY_PATH}/.docker-grafana-local/grafana/config:/etc/docker-grafana-local
    command: --config /etc/docker-grafana-local/grafana.ini

  loki:
    container_name: grafana-loki
    image: grafana/loki:1.5.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    container_name: grafana-promtail
    image: grafana/promtail:1.5.0
    volumes:
      - ${SHARED_DIRECTORY_PATH}/.docker-grafana-local/promtail/log:/var/promtail/log
      # TODO put the config file somewhere else than /var which doesn't seem like the best place for a config file
      - ${SHARED_DIRECTORY_PATH}/.docker-grafana-local/promtail/config:/etc/docker-grafana-local
    command: -config.file=/etc/docker-grafana-local/docker-config.yaml
    networks:
      - loki

networks:
  loki:

volumes:
  grafana:
