version: '3.6'

services:

    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginx
        restart: always
        ports:
            - "3005:80"
        volumes:
            - ./demo-app/usr/share/nginx/html:/usr/share/nginx/html
            - ./demo-app/etc/nginx/conf.d:/etc/nginx/conf.d
