version: '3.1'

services:

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  adminer:
    container_name: mariadb10.3-adminer
    image: adminer
    restart: always
    ports:
      - 8184:8080
