version: '3.5'

services:

    mysql:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306
        networks:
            - network_mysql
        volumes:
            - mysql:/var/lib/mysql
            - ${SHARED_DIRECTORY_PATH}/.docker-mysql-local:/var/docker-mysql-local

    adminer:
        container_name: mysql-adminer
        image: adminer
        restart: always
        ports:
            - 8182:8080
        networks:
            - network_mysql

    phpmyadmin:
        container_name: mysql-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8183:80
        networks:
            - network_mysql
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root

networks:
    network_mysql:
        name: network_mysql
        driver: bridge

volumes:
    mysql:
