version: '3.5'

services:

    redis:
        container_name: redis
        image: redis
        hostname: redis
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data/redis

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 8081:8081

volumes:
    redis_data:
        driver: local
